# Generated by Django 4.2.19 on 2025-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Rest_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='password',
            field=models.CharField(default='rest@123', max_length=30),
        ),
    ]
