# Generated by Django 4.2.21 on 2025-06-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Rest_Api', '0002_registermodel_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
