# Generated by Django 4.2.21 on 2025-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Rest_Api', '0003_delete_registermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
