# Generated by Django 4.2.21 on 2025-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Rest_Api', '0004_postmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
