# Generated by Django 4.2.21 on 2025-06-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Rest_Api', '0005_alter_postmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='email',
        ),
    ]
